package com.petreg.prototype.model.type;

public enum PetLifeCycleEvent {
    REGISTRATION,
    OWNER_CHANGE_STARTED,
    OWNER_CHANGE_CONFIRMED,
    LOST_REPORTED,
    FOUND_IN_SHELTER,
    MEDICAL_CHECKUP,
    TREATMENT_RECORDED,
    DEATH_REPORTED,
    PERMANENT_EXPORT
}
