# Development specific configuration

# JPA/Hibernate configuration
spring.jpa.properties.hibernate.format_sql=true

# Detailed SQL logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
